apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: msy7fxykn-nodejs 
  janus-idp.io/tekton: msy7fxykn-nodejs
  backstage.io/kubernetes-id: msy7fxykn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: msy7fxykn-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  