apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: msy7fxykn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: msy7fxykn-nodejs 
  name: msy7fxykn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: msy7fxykn-nodejs 
